[versions]
agp = "8.4.0"
androidx-annotation = "1.7.1"
androidx-test-runner = "1.5.2"
androidx-rest-rules = "1.5.0"
# noinspection GradleDependency
commons-io = "2.6"
# noinspection GradleDependency
commons-text = "1.3"
desugar = "2.0.4"
dokka = "1.9.20"
ezvcard = "0.12.1"
kotlin = "1.9.24"
junit = "4.13.2"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-rest-rules" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
ezvcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ezvcard" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
